create table department(d_id varchar(20) primary key, d_name varchar(20), program varchar(20), location varchar(50) not null);
create table student(srn varchar(20) primary key, name varchar(20) not null, semester int not null, karma_points int);
create table courses(c_id varchar(20) primary key, c_name varchar(50) unique, year int not null, semester int not null, anchor varchar(20) , course_info bytea );
create table professor(e_id varchar(20) primary key, name varchar(20) not null,email varchar(20) ,about varchar(150), domain varchar(50));
create table videos(v_id varchar(20) primary key, title varchar(20), duration int not null, description varchar(150), time_upload time, date_upload date);
create table topic(t_id varchar(20) primary key, professor varchar(20) not null, name varchar(20) not null,no_of_videos int ,no_of_followers int);
create table discussion_forum(f_id varchar(20) primary key, start_date date not null);
create table questions(q_id varchar(20) primary key, question varchar(200) not null, date_added date not null);
create table answers(a_id varchar(20) primary key, date_added date not null,  upvote int, answer varchar(1000));
create table admin(user_id varchar(20) primary key, password varchar(20));
create table student_follows_topic();
create table student_views_videos();
create table professor_offers_courses();
alter table student add column d_id varchar(20) references department;
alter table courses add column d_id varchar(20) references department;
alter table professor add column d_id varchar(20) references department;
alter table videos add column e_id varchar(20) references professor;
alter table discussion_forum add column v_id varchar(20) references videos;
alter table topic add column c_id varchar(20) references courses;
alter table questions add column e_id varchar(20) references professor;
alter table questions add column f_id varchar(20) references discussion_forum;
alter table questions add column srn varchar(20) references student;
alter table answers add column srn varchar(20) references student;
alter table answers add column q_id varchar(20) references questions;
alter table answers add column e_id varchar(20) references professor;
alter table student_follows_topic add column srn varchar(20) references student;
alter table student_follows_topic add column t_id varchar(20) references topic;
alter table student_views_videos add column srn varchar(20) references student;
alter table student_views_videos add column v_id varchar(20) references videos;
alter table professor_offers_courses add column e_id varchar(20) references professor;
alter table professor_offers_courses add column c_id varchar(20) references courses;

